language: php
php:
  - 5.6
  - 5.5
  - 7
  - hhvm
# run build against PHP 5.4 but allow them to fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.4
install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer update
  - composer info --installed
before_script:
  - mysql -e 'create database yii2_common_test;'
  - cd tests  
  - php ./codeception/bin/yii  migrate/up --interactive=0
  - ../vendor/bin/codecept build
script: ../vendor/bin/codecept run unit --debug
